version: '3.4'

services:
  mongodb:
    image: mongo


  customer.api:
    image: ${DOCKER_REGISTRY-}customerapi
    build:
      context: .
      dockerfile: Customer.API/Dockerfile

volumes:
  mongo_data: